### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by BlueGhostZ** [Wcsa23187/UBA#1]
Hi, author. Many thanks for publicizing such excellent work. I tried to run the main.py file in my device but encountered an error:
FileNotFoundError: [Errno 2] No such file or directory: './data/ml1m/pred_after.csv'

Is there any additional operation required to construct 'pred_after.csv', or can I get the file from another source?

**Comment by Wcsa23187** [comment]
Thanks for your question, we will update a new version of the codes soon.
